name: app1f
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
   day_night_switcher: ^0.2.0+1
   http: ^1.1.0
   shared_preferences: ^2.2.1
   table_calendar: ^3.0.9
   get: ^4.6.6
   sqflite: ^2.3.0
   flutter_slider_drawer: ^2.1.3
   path_provider: ^2.1.1
   flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
