name: app1f
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
   day_night_switcher: ^0.2.0+1
   google_maps_flutter: ^2.2.5
   flutter_cache_manager: ^3.3.1
   cached_network_image: ^3.3.0
   geolocator: ^10.1.0
   timezone: ^0.9.2
   firebase_core: ^2.21.0
   firebase_auth: ^4.12.1
   firebase_storage: ^11.4.1
   cloud_firestore: ^4.12.2
   provider: ^6.0.5
   flutter_map: ^6.0.1
   http: ^1.1.0
   shared_preferences: ^2.2.1
   flutter_local_notifications: ^16.1.0
   flutter_rating_bar: ^4.0.1
   circular_image: ^0.0.6
   youtube_player_flutter: ^8.1.2
   table_calendar: ^3.0.1
   get: ^4.6.6
   sqflite: ^2.3.0
   flutter_slider_drawer: ^2.1.3
   fluttertoast: ^8.2.2
   path_provider: ^2.1.1
   flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
